"use client";

import { useMemo, useState } from "react";
import { Sparkles } from "lucide-react";

import { InsightCard } from "@/components/dashboard/InsightCard";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { DatasetPill } from "@/components/dashboard/DatasetPill";
import { RichText } from "@/components/ai/RichText";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { Tabs } from "@/components/ui/Tabs";
import { useAiStatus } from "@/hooks/useAiStatus";
import { useDataset } from "@/hooks/useDataset";
import { useToast } from "@/hooks/useToast";
import { askDataForge } from "@/services/aiService";
import type { InsightCategory } from "@/types";

const CATEGORY_TABS: { value: InsightCategory | "all"; label: string }[] = [
  { value: "all", label: "All" },
  { value: "finding", label: "Key Findings" },
  { value: "trend", label: "Trends" },
  { value: "anomaly", label: "Anomalies" },
  { value: "opportunity", label: "Opportunities" },
  { value: "recommendation", label: "Recommendations" },
];

export default function InsightsPage() {
  const { dataset, insights } = useDataset();
  const { status } = useAiStatus();
  const toast = useToast();

  const [tab, setTab] = useState<string>("all");
  const [narrative, setNarrative] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const counts = useMemo(() => {
    const map = new Map<string, number>();
    for (const insight of insights) map.set(insight.category, (map.get(insight.category) ?? 0) + 1);
    return map;
  }, [insights]);

  const filtered = tab === "all" ? insights : insights.filter((insight) => insight.category === tab);

  const generateNarrative = async () => {
    setLoading(true);
    try {
      const response = await askDataForge({
        question:
          "Write an executive briefing of this dataset: what is happening, what changed, what is unusual and what should the team do next.",
        dataset,
      });
      setNarrative(response.message);
      toast.success(
        "Briefing generated",
        response.mode === "openai" ? "Written by the OpenAI engine." : "Written by the local demo engine.",
      );
    } catch {
      toast.error("Could not generate the briefing", "Please try again in a moment.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <PageHeader
        eyebrow="AI Insights"
        title="What your data is telling you"
        description="Every card below is produced by a detector that found real evidence in your dataset. Figures are recomputed on each dataset change."
        actions={
          <Button
            icon={<Sparkles className="h-4 w-4" />}
            loading={loading}
            onClick={() => void generateNarrative()}
          >
            Generate briefing
          </Button>
        }
      />

      <div className="flex flex-wrap items-center gap-3">
        <DatasetPill />
        <Badge tone={status.mode === "openai" ? "success" : "violet"} dot pulse>
          {status.mode === "openai" ? `OpenAI - ${status.model}` : "Local analysis engine"}
        </Badge>
      </div>

      {narrative ? (
        <Card highlight>
          <CardHeader
            icon={<Sparkles className="h-4 w-4" />}
            title="Executive briefing"
            description={status.mode === "openai" ? "Generated with OpenAI" : "Generated by the demo engine"}
            actions={
              <Button variant="ghost" size="sm" onClick={() => setNarrative(null)}>
                Dismiss
              </Button>
            }
          />
          <CardBody>
            <RichText content={narrative} />
          </CardBody>
        </Card>
      ) : null}

      <Tabs
        items={CATEGORY_TABS.map((tabItem) => ({
          value: tabItem.value,
          label: tabItem.label,
          count: tabItem.value === "all" ? insights.length : counts.get(tabItem.value) ?? 0,
        }))}
        value={tab}
        onChange={setTab}
        className="w-full sm:w-fit"
      />

      {filtered.length === 0 ? (
        <EmptyState
          icon={<Sparkles className="h-5 w-5" />}
          title="No insights in this category"
          description="Detectors only produce a card when they find real evidence. Try another category, or load a dataset with a date column and more numeric measures."
        />
      ) : (
        <section className="grid gap-4 lg:grid-cols-2">
          {filtered.map((insight, index) => (
            <InsightCard key={insight.id} insight={insight} index={index} />
          ))}
        </section>
      )}

      <Card>
        <CardBody className="text-[12.5px] leading-relaxed text-ink-muted">
          <span className="font-medium text-ink">How these are produced.</span> Seven detectors run over
          the profiled dataset: trend (opening vs. closing third), retention (orders minus new
          customers), concentration (top group share), anomaly (z-score and interquartile range),
          correlation (strongest Pearson pair), efficiency (revenue per unit of spend) and quality. A
          detector returns nothing when the evidence is not there - so an empty category is a real
          result, not a failure.
        </CardBody>
      </Card>
    </>
  );
}
